"""Phase 3 schema updates

Revision ID: 00bab7eee53c
Revises: b1c0eaa47eb3
Create Date: 2026-09-22 15:39:17.484158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00bab7eee53c'
down_revision: Union[str, Sequence[str], None] = 'b1c0eaa47eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('action_id', sa.String(), nullable=False))
    op.add_column('approvals', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('approvals', sa.Column('requested_at', sa.DateTime(), nullable=True))
    op.add_column('approvals', sa.Column('risk_level', sa.Integer(), nullable=True))
    op.add_column('approvals', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('approvals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('approvals', sa.Column('decision_at', sa.DateTime(), nullable=True))
    op.add_column('approvals', sa.Column('decision_source', sa.String(), nullable=True))
    op.add_column('approvals', sa.Column('action_parameters', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('approvals_step_id_fkey'), 'approvals', type_='foreignkey')
    op.create_foreign_key(None, 'approvals', 'plans', ['plan_id'], ['id'])
    op.drop_column('approvals', 'step_id')
    op.drop_column('approvals', 'decision')
    op.drop_column('approvals', 'approved_by')
    op.drop_column('approvals', 'timestamp')
    op.add_column('snapshots', sa.Column('action_id', sa.String(), nullable=False))
    op.add_column('snapshots', sa.Column('original_path', sa.String(), nullable=False))
    op.add_column('snapshots', sa.Column('snapshot_path', sa.String(), nullable=True))
    op.add_column('snapshots', sa.Column('original_hash', sa.String(), nullable=True))
    op.add_column('snapshots', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('operation_type', sa.String(), nullable=False))
    op.add_column('snapshots', sa.Column('restoration_status', sa.String(), nullable=True))
    op.drop_column('snapshots', 'path')
    op.drop_column('snapshots', 'status')
    op.drop_column('snapshots', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('snapshots', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('snapshots', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('snapshots', 'restoration_status')
    op.drop_column('snapshots', 'operation_type')
    op.drop_column('snapshots', 'size_bytes')
    op.drop_column('snapshots', 'original_hash')
    op.drop_column('snapshots', 'snapshot_path')
    op.drop_column('snapshots', 'original_path')
    op.drop_column('snapshots', 'action_id')
    op.add_column('approvals', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('approvals', sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('approvals', sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('approvals', sa.Column('step_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.create_foreign_key(op.f('approvals_step_id_fkey'), 'approvals', 'plan_steps', ['step_id'], ['id'])
    op.drop_column('approvals', 'action_parameters')
    op.drop_column('approvals', 'decision_source')
    op.drop_column('approvals', 'decision_at')
    op.drop_column('approvals', 'status')
    op.drop_column('approvals', 'reason')
    op.drop_column('approvals', 'risk_level')
    op.drop_column('approvals', 'requested_at')
    op.drop_column('approvals', 'plan_id')
    op.drop_column('approvals', 'action_id')
    # ### end Alembic commands ###
