"""Add plan step dependencies

Revision ID: b1c0eaa47eb3
Revises: 80db31e8098c
Create Date: 2026-09-22 15:25:10.829947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c0eaa47eb3'
down_revision: Union[str, Sequence[str], None] = '80db31e8098c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_steps', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plan_steps', sa.Column('dependencies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_steps', 'dependencies')
    op.drop_column('plan_steps', 'name')
    # ### end Alembic commands ###
